[package]
name = "nn_scratch"
version = "0.1.0"
edition = "2024"

authors = ["HRW Neuroinformatik Project"]
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
linalg_scratch = { path = "../linalg_scratch" }
